=== skukla/chef-vm-builder/app/core/schemas/config.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "VM Configuration",
  "required": [
    "vm",
    "application",
    "remote_machine"
  ],
  "type": "object",
  "properties": {
    "vm": {
      "$ref": "./vm/root.json"
    },
    "custom_demo": {
      "$ref": "./custom_demo/root.json"
    },
    "application": {
      "$ref": "./application/root.json"
    },
    "infrastructure": {
      "$ref": "./infrastructure/root.json"
    },
    "provisioner": {
      "$ref": "./provisioner/root.json"
    },
    "remote_machine": {
      "$ref": "./remote_machine/root.json"
    }
  },
  "additionalProperties": false
}

=== skukla/chef-vm-builder/user/config/config-b2b.json
{
  "vm": {
    "name": "Brentmill VM",
    "hypervisor": "virtualbox"
  },
  "custom_demo": {
    "structure": {
      "websites": [
        {
          "site_code": "base",
          "site_url": "brentmill.demo",
          "stores": [
            {
              "store_views": [
                {
                  "store_view_code": "default"
                }
              ]
            }
          ]
        }
      ]
    },
    "custom_modules": [
      {
        "source": "git@github.com:PMET-public/module-data-install.git"
      },
      {
        "source": "git@github.com:PMET-public/magento-scripts.git",
        "version": "2.3.0.x-dev"
      },
      {
        "source": "git@github.com:PMET-public/module-autofill.git"
      },
      {
        "source": "git@github.com:PMET-public/module-autofill-sample-data.git",
        "version": "dev-b2b"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-catalog-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-media-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-legrand-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-milwaukee-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-philips-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-siemens-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-misc-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-admin-configurations.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-b2c-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-cms-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-company-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-sales-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-order-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-pricing-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-b2b-shared-catalog-sample-data.git"
      },
      {
        "source": "git@github.com:PMET-public/module-my-account-widget.git"
      },
      {
        "source": "git@github.com:PMET-public/theme-brentmill.git"
      }
    ]
  },
  "application": {
    "authentication": {
      "composer": {
        "public_key": "9aec72c4ae091290105b1624e46ba2f4",
        "private_key": "32d399998cc65508e7aa406245a21876",
        "github_token": "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"
      }
    },
    "options": {
      "version": "2.4.3-p1"
    },
    "build": {
      "action": "force_install",
      "restore": "separate",
      "sample_data": false,
      "patches": true,
      "hooks": {
        "warm_cache": false,
        "enable_media_gallery": true,
        "backup": true,
        "commands": [
          "vendor/magentoese/magento-scripts/composer-setup.sh b2b"
        ]
      }
    },
    "settings": {
      "admin_password": "admin4tls"
    }
  },
  "remote_machine": {
    "cpus": "2",
    "memory": "8192"
  }
}

=== skukla/chef-vm-builder/user/config/config.json
{
	"vm": {
		"name": "Luma VM",
		"hypervisor": "virtualbox"
	},
	"custom_demo": {
		"structure": {
			"websites": [
				{
					"site_code": "base",
					"site_url": "luma.demo",
					"stores": [
						{
							"store_views": [
								{
									"store_view_code": "default"
								},
								{
									"store_view_code": "custom_store_view_ca_fr",
									"store_view_url": "fr.luma.ca"
								}
							]
						},
						{
							"store_views": [
								{
									"store_view_code": "custom_store_view_us_en",
									"store_view_url": "custom.luma.demo"
								}
							]
						}
					]
				},
				{
					"site_code": "custom_b2b_website",
					"site_url": "b2b.luma.demo",
					"stores": [
						{
							"store_views": [
								{
									"store_view_code": "custom_b2b_en_us"
								}
							]
						}
					]
				}
			]
		},
		"data_packs": [],
		"custom_modules": []
	},
	"application": {
		"authentication": {
			"composer": {
				"public_key": "9aec72c4ae091290105b1624e46ba2f4",
				"private_key": "32d399998cc65508e7aa406245a21876",
				"github_token": "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"
			}
		},
		"options": {
			"version": "2.4.4"
		},
		"build": {
			"action": "force_install",
			"restore": "separate",
			"sample_data": false,
			"patches": true,
			"hooks": {
				"warm_cache": false,
				"backup": false
			}
		},
		"settings": {
			"admin_password": "admin4tls"
		}
	},
	"infrastructure": {
		"php": "8.1",
		"search_engine": "elasticsearch"
	},
	"remote_machine": {
		"cpus": "2",
		"memory": "8192"
	}
}

=== skukla/chef-vm-builder/user/config/config-tmobile.json
{
	"vm": {
		"name": "T-Mobile VM",
		"hypervisor": "virtualbox"
	},
	"custom_demo": {
		"structure": {
			"websites": [
				{
					"site_code": "base",
					"site_url": "tmobile.demo",
					"stores": [
						{
							"store_views": [
								{
									"store_view_code": "default"
								}
							]
						}
					]
				}
			]
		},
		"data_packs": [
			{
				"source": "https://github.com/skukla/module-tmo-datapack.git",
				"data": [
					{
						"data_path": "tmobile-store"
					}
				]
			}
		],
		"custom_modules": [
			{
				"source": "https://github.com/PMET-public/module-data-install.git"
			},
			{
				"source": "https://github.com/PMET-public/paradoxlabs-tokenbase.git",
				"version": "4.3.8.x-dev"
			},
			{
				"source": "https://github.com/PMET-public/paradoxlabs-subscriptions.git",
				"version": "3.3.4.x-dev"
			},
			{
				"source": "https://github.com/PMET-public/module-autofill.git"
			}
		]
	},
	"application": {
		"authentication": {
			"composer": {
				"public_key": "9aec72c4ae091290105b1624e46ba2f4",
				"private_key": "32d399998cc65508e7aa406245a21876",
				"github_token": "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"
			}
		},
		"options": {
			"version": "2.4.3-p1"
		},
		"build": {
			"action": "force_install",
			"restore": "separate",
			"sample_data": false,
			"patches": true,
			"hooks": {
				"warm_cache": false,
				"enable_media_gallery": true,
				"backup": false
			}
		},
		"settings": {
			"admin_password": "admin4tls"
		}
	},
	"infrastructure": {
		"search_engine": "elasticsearch"
	},
	"remote_machine": {
		"cpus": "2",
		"memory": "8192"
	}
}
